version: '3.9'

services:
  database:
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=iamoderation
